
version: 2

models:
  - name: my_first_dbt_model
    description: "NYCタクシートリップのデータ（モデル）。ピックアップ日時、ドロップオフ日時、乗車距離、運賃、ピックアップZIP、ドロップオフZIPを含む。"
    columns:
      - name: tpep_pickup_datetime
        description: "ピックアップ日時"
      - name: tpep_dropoff_datetime
        description: "ドロップオフ日時"
      - name: trip_distance
        description: "乗車距離"
      - name: fare_amount
        description: "運賃"
      - name: pickup_zip
        description: "ピックアップZIPコード"
      - name: dropoff_zip
        description: "ドロップオフZIPコード"
