version: 2

sources:
  - name: nyctaxi
    database: samples
    schema: nyctaxi
    tables:
      - name: trips
        description: "NYCタクシートリップのデータ（ソース）。ピックアップ日時、ドロップオフ日時、乗車距離、運賃、ピックアップZIP、ドロップオフZIPを含む。"
        columns:
          - name: tpep_pickup_datetime
            description: "ピックアップ日時 (timestamp)"
          - name: tpep_dropoff_datetime
            description: "ドロップオフ日時 (timestamp)"
          - name: trip_distance
            description: "乗車距離 (double)"
          - name: fare_amount
            description: "運賃 (double)"
          - name: pickup_zip
            description: "ピックアップZIPコード (integer)"
          - name: dropoff_zip
            description: "ドロップオフZIPコード (integer)"
